@startuml
entity "Материал" as Material {
  * ID : int
  --
  Title : nvarchar
  CountInStock : float
  MinCount : float
  Cost : decimal
  MaterialTypeID : int
}
entity "Тип материала" as MaterialType {
  * ID : int
  --
  Title : nvarchar
  DefectedPercent : float
}
entity "Поставщик" as Supplier {
  * ID : int
  --
  Title : nvarchar
  INN : varchar
}
entity "Связь материал-поставщик" as MaterialSupplier {
  * MaterialID : int
  * SupplierID : int
}
entity "История остатков" as MaterialCountHistory {
  * ID : int
  --
  MaterialID : int
  ChangeDate : datetime
  CountValue : float
}
entity "Продукция" as Product {
  * ID : int
  --
  Title : nvarchar
}
entity "Материалы продукции" as ProductMaterial {
  * ProductID : int
  * MaterialID : int
  Count : float
}
Material }o--|| MaterialType
Material ||--o{ MaterialSupplier
Supplier ||--o{ MaterialSupplier
Material ||--o{ MaterialCountHistory
Material ||--o{ ProductMaterial
Product ||--o{ ProductMaterial
@enduml
